export const SCHEMA_STATEMENTS: string[] = [
  "DROP TABLE IF EXISTS \"CoachNote\" CASCADE",
  "CREATE TABLE public.\"Account\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    type text NOT NULL,\n    provider text NOT NULL,\n    \"providerAccountId\" text NOT NULL,\n    refresh_token text,\n    access_token text,\n    expires_at integer,\n    token_type text,\n    scope text,\n    id_token text,\n    session_state text\n)",
  "CREATE TABLE public.\"AiUsage\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    date date NOT NULL,\n    generations integer DEFAULT 0 NOT NULL\n)",
  "CREATE TABLE public.\"AnalyticsSnapshot\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    date date NOT NULL,\n    \"profileViews\" integer DEFAULT 0 NOT NULL,\n    \"postImpressions\" integer DEFAULT 0 NOT NULL,\n    followers integer DEFAULT 0 NOT NULL,\n    connections integer DEFAULT 0 NOT NULL,\n    \"searchAppearances\" integer DEFAULT 0 NOT NULL,\n    \"engagementRate\" double precision DEFAULT 0 NOT NULL,\n    source text DEFAULT 'manual'::text NOT NULL,\n    \"rawData\" jsonb\n)",
  "CREATE TABLE public.\"ApiKey\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    label text DEFAULT 'Browser extension'::text NOT NULL,\n    prefix text NOT NULL,\n    \"hashedKey\" text NOT NULL,\n    \"lastUsedAt\" timestamp(3) without time zone,\n    \"revokedAt\" timestamp(3) without time zone,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL\n)",
  "CREATE TABLE public.\"BlogPost\" (\n    id text NOT NULL,\n    slug text NOT NULL,\n    title text NOT NULL,\n    excerpt text,\n    content text NOT NULL,\n    \"coverImage\" text,\n    author text DEFAULT 'LnkRise Team'::text NOT NULL,\n    tags text[] DEFAULT ARRAY[]::text[],\n    published boolean DEFAULT false NOT NULL,\n    \"publishedAt\" timestamp(3) without time zone,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    \"updatedAt\" timestamp(3) without time zone NOT NULL\n)",
  "CREATE TABLE public.\"CaseStudy\" (\n    id text NOT NULL,\n    slug text NOT NULL,\n    title text NOT NULL,\n    \"userName\" text NOT NULL,\n    \"userImage\" text,\n    \"userRole\" text,\n    \"beforeStats\" jsonb NOT NULL,\n    \"afterStats\" jsonb NOT NULL,\n    story text NOT NULL,\n    testimonial text,\n    published boolean DEFAULT false NOT NULL,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL\n)",
  "CREATE TABLE public.\"CoachNote\" (\n    id text NOT NULL,\n    \"coachId\" text NOT NULL,\n    \"clientId\" text NOT NULL,\n    body text NOT NULL,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL\n)",
  "CREATE TABLE public.\"CoachingTask\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    \"briefId\" text,\n    type text NOT NULL,\n    title text NOT NULL,\n    description text,\n    priority text DEFAULT 'medium'::text NOT NULL,\n    status text DEFAULT 'pending'::text NOT NULL,\n    \"dueDate\" timestamp(3) without time zone,\n    \"completedAt\" timestamp(3) without time zone,\n    \"aiData\" jsonb,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL\n)",
  "CREATE TABLE public.\"DailyBrief\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    date date NOT NULL,\n    content jsonb NOT NULL,\n    completed jsonb DEFAULT '{}'::jsonb NOT NULL,\n    score integer,\n    \"emailSent\" boolean DEFAULT false NOT NULL,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL\n)",
  "CREATE TABLE public.\"Fact\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    question text NOT NULL,\n    body text NOT NULL,\n    kind text NOT NULL,\n    \"lastUsedAt\" timestamp(3) without time zone,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    \"updatedAt\" timestamp(3) without time zone NOT NULL\n)",
  "CREATE TABLE public.\"Post\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    title text,\n    content text NOT NULL,\n    status text DEFAULT 'draft'::text NOT NULL,\n    \"scheduledAt\" timestamp(3) without time zone,\n    \"publishedAt\" timestamp(3) without time zone,\n    \"aiGenerated\" boolean DEFAULT false NOT NULL,\n    metrics jsonb,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    \"updatedAt\" timestamp(3) without time zone NOT NULL,\n    \"linkedinUrn\" text,\n    \"reminderSentAt\" timestamp(3) without time zone\n)",
  "CREATE TABLE public.\"Session\" (\n    id text NOT NULL,\n    \"sessionToken\" text NOT NULL,\n    \"userId\" text NOT NULL,\n    expires timestamp(3) without time zone NOT NULL\n)",
  "CREATE TABLE public.\"Subscription\" (\n    id text NOT NULL,\n    \"userId\" text NOT NULL,\n    \"stripeCustomerId\" text,\n    \"stripePriceId\" text,\n    \"stripeSubscriptionId\" text,\n    status text DEFAULT 'trialing'::text NOT NULL,\n    plan text DEFAULT 'trial'::text NOT NULL,\n    \"trialEndsAt\" timestamp(3) without time zone,\n    \"currentPeriodEnd\" timestamp(3) without time zone,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    \"updatedAt\" timestamp(3) without time zone NOT NULL\n)",
  "CREATE TABLE public.\"User\" (\n    id text NOT NULL,\n    email text NOT NULL,\n    \"emailVerified\" timestamp(3) without time zone,\n    name text,\n    image text,\n    role text DEFAULT 'user'::text NOT NULL,\n    \"linkedinUrl\" text,\n    \"linkedinData\" jsonb,\n    \"onboardingData\" jsonb,\n    strategy jsonb,\n    inspirations text[] DEFAULT ARRAY[]::text[],\n    \"growthScore\" integer DEFAULT 0 NOT NULL,\n    streak integer DEFAULT 0 NOT NULL,\n    \"longestStreak\" integer DEFAULT 0 NOT NULL,\n    \"lastActiveAt\" timestamp(3) without time zone,\n    \"onboardedAt\" timestamp(3) without time zone,\n    language text DEFAULT 'en'::text NOT NULL,\n    timezone text DEFAULT 'UTC'::text NOT NULL,\n    \"emailBriefEnabled\" boolean DEFAULT true NOT NULL,\n    \"emailBriefHour\" integer DEFAULT 7 NOT NULL,\n    \"postingFrequency\" text DEFAULT '3_per_week'::text NOT NULL,\n    \"contentTone\" text DEFAULT 'professional'::text NOT NULL,\n    \"dailyTimeBudget\" integer DEFAULT 30 NOT NULL,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    \"updatedAt\" timestamp(3) without time zone NOT NULL,\n    \"connectionPlan\" jsonb,\n    \"brandColor\" text,\n    \"brandLogoUrl\" text,\n    \"brandName\" text,\n    \"coachId\" text\n)",
  "CREATE TABLE public.\"VerificationToken\" (\n    identifier text NOT NULL,\n    token text NOT NULL,\n    expires timestamp(3) without time zone NOT NULL\n)",
  "CREATE TABLE public.\"WaitlistEntry\" (\n    id text NOT NULL,\n    email text NOT NULL,\n    source text,\n    \"createdAt\" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL\n)",
  "ALTER TABLE ONLY public.\"Account\"\n    ADD CONSTRAINT \"Account_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"AiUsage\"\n    ADD CONSTRAINT \"AiUsage_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"AnalyticsSnapshot\"\n    ADD CONSTRAINT \"AnalyticsSnapshot_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"ApiKey\"\n    ADD CONSTRAINT \"ApiKey_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"BlogPost\"\n    ADD CONSTRAINT \"BlogPost_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"CaseStudy\"\n    ADD CONSTRAINT \"CaseStudy_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"CoachNote\"\n    ADD CONSTRAINT \"CoachNote_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"CoachingTask\"\n    ADD CONSTRAINT \"CoachingTask_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"DailyBrief\"\n    ADD CONSTRAINT \"DailyBrief_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"Fact\"\n    ADD CONSTRAINT \"Fact_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"Post\"\n    ADD CONSTRAINT \"Post_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"Session\"\n    ADD CONSTRAINT \"Session_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"Subscription\"\n    ADD CONSTRAINT \"Subscription_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"User\"\n    ADD CONSTRAINT \"User_pkey\" PRIMARY KEY (id)",
  "ALTER TABLE ONLY public.\"WaitlistEntry\"\n    ADD CONSTRAINT \"WaitlistEntry_pkey\" PRIMARY KEY (id)",
  "CREATE UNIQUE INDEX \"Account_provider_providerAccountId_key\" ON public.\"Account\" USING btree (provider, \"providerAccountId\")",
  "CREATE INDEX \"Account_userId_idx\" ON public.\"Account\" USING btree (\"userId\")",
  "CREATE INDEX \"AiUsage_userId_date_idx\" ON public.\"AiUsage\" USING btree (\"userId\", date DESC)",
  "CREATE UNIQUE INDEX \"AiUsage_userId_date_key\" ON public.\"AiUsage\" USING btree (\"userId\", date)",
  "CREATE INDEX \"AnalyticsSnapshot_userId_date_idx\" ON public.\"AnalyticsSnapshot\" USING btree (\"userId\", date DESC)",
  "CREATE UNIQUE INDEX \"AnalyticsSnapshot_userId_date_key\" ON public.\"AnalyticsSnapshot\" USING btree (\"userId\", date)",
  "CREATE UNIQUE INDEX \"ApiKey_hashedKey_key\" ON public.\"ApiKey\" USING btree (\"hashedKey\")",
  "CREATE INDEX \"ApiKey_userId_idx\" ON public.\"ApiKey\" USING btree (\"userId\")",
  "CREATE UNIQUE INDEX \"BlogPost_slug_key\" ON public.\"BlogPost\" USING btree (slug)",
  "CREATE UNIQUE INDEX \"CaseStudy_slug_key\" ON public.\"CaseStudy\" USING btree (slug)",
  "CREATE INDEX \"CoachNote_coachId_clientId_idx\" ON public.\"CoachNote\" USING btree (\"coachId\", \"clientId\")",
  "CREATE INDEX \"CoachingTask_briefId_idx\" ON public.\"CoachingTask\" USING btree (\"briefId\")",
  "CREATE INDEX \"CoachingTask_userId_status_idx\" ON public.\"CoachingTask\" USING btree (\"userId\", status)",
  "CREATE INDEX \"DailyBrief_userId_date_idx\" ON public.\"DailyBrief\" USING btree (\"userId\", date DESC)",
  "CREATE UNIQUE INDEX \"DailyBrief_userId_date_key\" ON public.\"DailyBrief\" USING btree (\"userId\", date)",
  "CREATE INDEX \"Fact_userId_createdAt_idx\" ON public.\"Fact\" USING btree (\"userId\", \"createdAt\" DESC)",
  "CREATE UNIQUE INDEX \"Post_linkedinUrn_key\" ON public.\"Post\" USING btree (\"linkedinUrn\")",
  "CREATE INDEX \"Post_status_scheduledAt_idx\" ON public.\"Post\" USING btree (status, \"scheduledAt\")",
  "CREATE INDEX \"Post_userId_publishedAt_idx\" ON public.\"Post\" USING btree (\"userId\", \"publishedAt\" DESC)",
  "CREATE INDEX \"Post_userId_status_idx\" ON public.\"Post\" USING btree (\"userId\", status)",
  "CREATE UNIQUE INDEX \"Session_sessionToken_key\" ON public.\"Session\" USING btree (\"sessionToken\")",
  "CREATE INDEX \"Session_userId_idx\" ON public.\"Session\" USING btree (\"userId\")",
  "CREATE UNIQUE INDEX \"Subscription_stripeCustomerId_key\" ON public.\"Subscription\" USING btree (\"stripeCustomerId\")",
  "CREATE UNIQUE INDEX \"Subscription_stripeSubscriptionId_key\" ON public.\"Subscription\" USING btree (\"stripeSubscriptionId\")",
  "CREATE UNIQUE INDEX \"Subscription_userId_key\" ON public.\"Subscription\" USING btree (\"userId\")",
  "CREATE INDEX \"User_coachId_idx\" ON public.\"User\" USING btree (\"coachId\")",
  "CREATE INDEX \"User_createdAt_idx\" ON public.\"User\" USING btree (\"createdAt\")",
  "CREATE UNIQUE INDEX \"User_email_key\" ON public.\"User\" USING btree (email)",
  "CREATE INDEX \"User_role_idx\" ON public.\"User\" USING btree (role)",
  "CREATE INDEX \"User_timezone_emailBriefHour_idx\" ON public.\"User\" USING btree (timezone, \"emailBriefHour\")",
  "CREATE UNIQUE INDEX \"VerificationToken_identifier_token_key\" ON public.\"VerificationToken\" USING btree (identifier, token)",
  "CREATE UNIQUE INDEX \"VerificationToken_token_key\" ON public.\"VerificationToken\" USING btree (token)",
  "CREATE UNIQUE INDEX \"WaitlistEntry_email_key\" ON public.\"WaitlistEntry\" USING btree (email)",
  "ALTER TABLE ONLY public.\"Account\"\n    ADD CONSTRAINT \"Account_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"AiUsage\"\n    ADD CONSTRAINT \"AiUsage_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"AnalyticsSnapshot\"\n    ADD CONSTRAINT \"AnalyticsSnapshot_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"ApiKey\"\n    ADD CONSTRAINT \"ApiKey_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"CoachingTask\"\n    ADD CONSTRAINT \"CoachingTask_briefId_fkey\" FOREIGN KEY (\"briefId\") REFERENCES public.\"DailyBrief\"(id) ON UPDATE CASCADE ON DELETE SET NULL",
  "ALTER TABLE ONLY public.\"CoachingTask\"\n    ADD CONSTRAINT \"CoachingTask_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"DailyBrief\"\n    ADD CONSTRAINT \"DailyBrief_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"Fact\"\n    ADD CONSTRAINT \"Fact_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"Post\"\n    ADD CONSTRAINT \"Post_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"Session\"\n    ADD CONSTRAINT \"Session_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"Subscription\"\n    ADD CONSTRAINT \"Subscription_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE CASCADE",
  "ALTER TABLE ONLY public.\"User\"\n    ADD CONSTRAINT \"User_coachId_fkey\" FOREIGN KEY (\"coachId\") REFERENCES public.\"User\"(id) ON UPDATE CASCADE ON DELETE SET NULL"
];
